"""
Authentication API Routes.

Endpoints:
- POST /api/v1/auth/login - User login
- POST /api/v1/auth/register - User registration
- POST /api/v1/auth/refresh - Token refresh
- GET /api/v1/auth/me - Get current user
"""

from fastapi import APIRouter, Depends, HTTPException, status
from loguru import logger

from api.auth import (
    auth_manager,
    get_current_user,
    LoginRequest,
    RegisterRequest,
    Token,
    User
)

router = APIRouter()


@router.post("/login", response_model=Token)
async def login(request: LoginRequest):
    """
    User login endpoint.
    
    Authenticates user and returns JWT access token.
    
    Args:
        request: Login credentials (username, password)
        
    Returns:
        JWT access token
        
    Raises:
        401: Invalid credentials
    """
    user = await auth_manager.authenticate_user(
        username=request.username,
        password=request.password
    )
    
    if not user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect username or password",
            headers={"WWW-Authenticate": "Bearer"},
        )
    
    # Create access token
    access_token = auth_manager.create_access_token(
        data={
            "sub": user.user_id,
            "username": user.username,
            "roles": user.roles
        }
    )
    
    # Create refresh token
    refresh_token = auth_manager.create_refresh_token(
        data={
            "sub": user.user_id,
            "username": user.username,
            "roles": user.roles
        }
    )
    
    logger.info(f"User logged in: {user.username}")
    
    return Token(
        access_token=access_token,
        token_type="bearer",
        expires_in=auth_manager.access_token_expire_minutes * 60
    )


@router.post("/register", response_model=User, status_code=status.HTTP_201_CREATED)
async def register(request: RegisterRequest):
    """
    User registration endpoint.
    
    Creates new user account.
    
    Args:
        request: Registration data (username, email, password)
        
    Returns:
        Created user
        
    Raises:
        400: User already exists
        
    Note: This is a placeholder implementation.
    """
    # Check if user already exists
    existing_user = await auth_manager.get_user(request.username)
    if existing_user:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Username already registered"
        )
    
    # Hash password
    hashed_password = auth_manager.hash_password(request.password)
    
    # Create user (placeholder - implement actual database insert)
    new_user = User(
        user_id="generated-id",  # Should be generated by database
        username=request.username,
        email=request.email,
        roles=["user"],
        is_active=True
    )
    
    logger.info(f"User registered: {new_user.username}")
    
    return new_user


@router.post("/refresh", response_model=Token)
async def refresh_token(refresh_token: str):
    """
    Token refresh endpoint.
    
    Refreshes access token using refresh token.
    
    Args:
        refresh_token: Valid refresh token
        
    Returns:
        New access token
        
    Raises:
        401: Invalid refresh token
    """
    return await auth_manager.refresh_access_token(refresh_token)


@router.get("/me", response_model=User)
async def get_me(current_user: User = Depends(get_current_user)):
    """
    Get current user endpoint.
    
    Returns information about the authenticated user.
    
    Args:
        current_user: Current authenticated user (from token)
        
    Returns:
        Current user information
        
    Requires:
        Valid JWT token in Authorization header
    """
    return current_user


@router.get("/protected")
async def protected_endpoint(current_user: User = Depends(get_current_user)):
    """
    Example protected endpoint.
    
    Requires authentication.
    
    Args:
        current_user: Current authenticated user
        
    Returns:
        Protected data
    """
    return {
        "message": "This is a protected endpoint",
        "user": current_user.username,
        "roles": current_user.roles
    }
